### PR TITLE
Css/related

### PR DESCRIPTION
**Pull request by Xinyi2022**
- fixed review star for each product
- each product has its unique review
http://g.recordit.co/TPrLVeNTPi.gif

### CODE REVIEW

**Comment by cmoralespv** [comment]
Xinyi... did you pull the latest main branch before this pull? There have been various modifications for it to work on AWS...

**Comment by cmoralespv** [comment]
my previous comment is just a question by the way :-) Not because I found an error.. just want to make sure before we merge

**Comment by Xinyi2022** [comment]
yes, I did pull from main and then pushed to my branch. I didn't see any conflict, so I guess should be fine.

**Comment by Xinyi2022** [comment]
[Fixed review star for related list and outfit list.](https://trello.com/c/fz5DLZ0P/90-fixed-review-star-for-related-list-and-outfit-list)

**Comment by cmoralespv** [comment]
Xinyi, I see that it was already merged... happy to see that!

**Pull request merged**
